# -*- coding: utf-8 -*-
"""速查手册全集 —— 面向高职一年级、尚未接触这些内容的备赛学生

分组原则：
  sec = 分区（Linux / Python / Java / MySQL / 大数据 / 赛场通用）
  group = 具体主题
  cmds = [命令, 说明]；★ 开头表示「必须记熟」，⚠ 开头表示「高危/易错」

目标：学生考前 30 分钟扫一遍就能捡回操作手感，赛场上忘了写法能立刻查到。
"""

CHEATS = [
    # ---------------- Linux ----------------
    {"sec": "Linux", "group": "目录与文件（★必背）", "cmds": [
        ["★pwd", "打印当前所在目录，迷路第一件事"],
        ["★cd /root/eduhq", "切到绝对路径；cd .. 上一级；cd ~ 回家；cd - 回上一次目录"],
        ["★ls -lh", "看详情，大小带 K/M/G 单位；ls -a 连隐藏文件一起看"],
        ["★mkdir -p /behavior/origin_log", "-p 级联创建，父目录不存在时一并建（赛题高频）"],
        ["cp -r 源 目标", "复制目录必须加 -r；cp a.txt b.txt 复制文件"],
        ["mv 旧名 新名", "移动或改名（同一目录下就是改名）"],
        ["⚠rm -rf 目录", "强制删除目录；**rm -rf / 是删库跑路，永远别敲**"],
        ["touch a.txt", "建空文件 / 更新时间戳"],
    ]},
    {"sec": "Linux", "group": "查看与检索", "cmds": [
        ["★cat a.txt", "全文输出（只适合小文件，大日志会把屏幕刷爆）"],
        ["head -20 a.txt", "看开头 20 行"],
        ["★tail -f 日志", "实时跟踪日志，服务起不来时盯报错用；Ctrl+C 退出"],
        ["★grep 'ERROR' 日志", "查关键词；grep -n 带行号；grep -v 反向排除"],
        ["find / -name 'hive-site.xml'", "按文件名全盘查找"],
        ["wc -l a.txt", "统计行数（赛题常要求报告处理了多少条）"],
        ["du -sh 目录", "看目录占多大；df -h 看磁盘剩余"],
    ]},
    {"sec": "Linux", "group": "重定向与管道（★必考）", "cmds": [
        ["★命令 > r.txt", "结果写进文件，**覆盖**原内容"],
        ["★命令 >> r.txt", "追加到文件末尾，不清空原内容"],
        ["★命令1 | 命令2", "管道：把前一个的输出交给后一个处理"],
        ["cat a.txt | grep x | wc -l", "经典组合：数一数有多少行含 x"],
        ["sort | uniq -c", "排序后去重计数（词频统计的 shell 版）"],
        ["awk '{print $1}' a.txt", "取第 1 列；awk -F',' 指定逗号为分隔符"],
        ["sed -i 's/旧/新/g' a.txt", "批量替换文本（-i 直接改文件）"],
    ]},
    {"sec": "Linux", "group": "权限与属主", "cmds": [
        ["★chmod +x start.sh", "给脚本加执行权限（写完脚本跑不起来基本都是忘了这句）"],
        ["chmod 755 文件", "属主 rwx / 同组 rx / 其他 rx（r=4 w=2 x=1）"],
        ["chown -R hadoop:hadoop /opt/bigdata", "递归改属主（-R 连子目录一起）"],
        ["ls -l", "第一列 -rwxr-xr-x：第 1 位类型，后 9 位 = 属主/属组/其他"],
        ["sudo 命令", "临时提权执行"],
    ]},
    {"sec": "Linux", "group": "进程与端口（装完先验活）", "cmds": [
        ["★jps", "Hadoop 全家桶体检表：NN/DN/RM/NM 在不在一眼看清"],
        ["★ss -lntp | grep 9870", "看端口是否被监听（没有 ss 就用 netstat -lntp）"],
        ["ps -ef | grep java", "找进程；kill -9 进程号 强杀"],
        ["systemctl status mysqld", "看服务状态；返回 unknown = 压根没这个单元"],
        ["systemctl start|stop|restart 服务", "启停服务"],
        ["systemctl enable 服务", "设开机自启"],
        ["top", "看 CPU/内存占用，q 退出"],
        ["free -h", "**备赛第一动作**：先看还剩多少内存"],
    ]},
    {"sec": "Linux", "group": "压缩与环境变量", "cmds": [
        ["★tar -zxvf x.tar.gz -C /opt/", "解压（-z gzip，-x 解压，-v 显示，-C 指定目录）"],
        ["tar -zcvf 包.tar.gz 目录", "打包压缩"],
        ["unzip x.zip -d /opt/", "解压 zip"],
        ["★source /etc/profile", "改完环境变量必须 source 才生效（新窗口也要 source）"],
        ["echo $HADOOP_HOME", "验证环境变量配好没有"],
        ["which hadoop", "看命令在不在 PATH 里"],
        ["vim /etc/profile.d/bigdata.sh", "推荐把环境变量写成独立文件，干净好维护"],
    ]},
    {"sec": "Linux", "group": "Vim 最小集（会这 6 个就够）", "cmds": [
        ["vim 文件名", "打开；不存在则新建"],
        ["i", "进入编辑模式（左下角出现 -- INSERT --）"],
        ["Esc", "退回命令模式"],
        ["★:wq", "保存并退出；:q! 不保存强制退出"],
        ["★/关键词", "向下搜索；n 下一个，N 上一个"],
        ["★:set nu", "显示行号；gg 到首行，G 到末行，:100 跳第 100 行"],
        ["dd", "删当前行；yy 复制；p 粘贴；u 撤销"],
    ]},
    {"sec": "Linux", "group": "SSH 与免密（集群前置）", "cmds": [
        ["ssh-keygen -t rsa", "生成密钥对（一路回车）"],
        ["★ssh-copy-id slave1", "把公钥发给对方，之后免密登录"],
        ["ssh slave1 'hostname'", "远程执行一条命令（批量操作很有用）"],
        ["scp -r /opt/bigdata slave1:/opt/", "远程复制目录"],
        ["⚠ssh slave1 报 Permission denied", "检查 ~/.ssh/authorized_keys 权限必须是 600"],
    ]},

    # ---------------- Python ----------------
    {"sec": "Python", "group": "运行与语法", "cmds": [
        ["python3 clean.py", "跑脚本（本机 3.7.9）"],
        ["python3", "进交互式 >>>，exit() 退出"],
        ["# -*- coding: utf-8 -*-", "文件头声明，防中文乱码"],
        ["★print(f'共 {n} 条')", "f-string 格式化输出"],
        ["len(a) / a[0] / a[1:3]", "长度 / 取首个（从 0 开始）/ 切片"],
        ["for i, row in df.iterrows():", "逐行遍历（数据少时最直观）"],
        ["with open('a.txt', encoding='utf-8') as f:", "读文件标准写法，with 自动关闭"],
    ]},
    {"sec": "Python", "group": "★pandas 数据处理（模块二核心）", "cmds": [
        ["★df = pd.read_csv('a.csv', encoding='utf-8')", "读 CSV；sep='\\t' 读制表符分隔"],
        ["★df.to_csv('r.csv', index=False)", "导出（**index=False 去掉行索引**，题目不要求就别带）"],
        ["df.head() / df.info() / df.shape", "前 5 行 / 列类型与空值 / 行列数"],
        ["df.describe()", "数值列统计摘要"],
        ["★df[df['age'] > 18]", "条件筛选；多条件用 & | 且**每个条件加括号**"],
        ["★df.dropna() / df.drop_duplicates()", "去空行 / 去重"],
        ["df.fillna(0) / df.astype(int)", "填空值 / 改列类型"],
        ["★df.groupby('province')['cnt'].sum()", "分组聚合（出图前必用）"],
        ["df.sort_values('cnt', ascending=False)", "排序；head(10) 取前 10"],
        ["df['日期'] = pd.to_datetime(df['日期'])", "转日期，之后 .dt.year / .dt.month 取年月"],
        ["df.columns = ['a','b','c']", "重命名列（题目常要求改表头）"],
        ["⚠len(df)", "赛题要求**结果文件名带处理条数 N**，别忘了统计"],
    ]},
    {"sec": "Python", "group": "出图：Matplotlib / Seaborn", "cmds": [
        ["★plt.rcParams['font.sans-serif'] = ['SimHei']", "**中文不乱码的两行，必写**"],
        ["★plt.rcParams['axes.unicode_minus'] = False", "解决负号显示为方块"],
        ["plt.figure(figsize=(12, 6))", "画布大小"],
        ["plt.plot(x, y) / plt.bar(x, y)", "折线 / 柱状；plt.scatter 散点，plt.pie 饼图"],
        ["plt.title('标题') / plt.xlabel('x') / plt.ylabel('y')", "标题与轴标签"],
        ["plt.legend() / plt.grid(alpha=0.3)", "图例 / 网格"],
        ["★plt.savefig('/root/eduhq/html/a.png', dpi=150)", "存图（**注意路径按题目要求**）"],
        ["plt.show()", "显示（服务器上一般省略）"],
        ["sns.set_theme(style='whitegrid')", "Seaborn 定风格"],
        ["sns.barplot(x='省', y='量', data=df)", "Seaborn 一行出图"],
    ]},
    {"sec": "Python", "group": "出图：Pyecharts（交互 HTML）", "cmds": [
        ["from pyecharts.charts import Bar, Line, Pie, Map, WordCloud", "按需导入图表类"],
        ["★bar = Bar().add_xaxis(列表).add_yaxis('系列名', 列表)", "链式写法，一步一 ."],
        ["bar.set_global_opts(title_opts=opts.TitleOpts(title='标题'))", "全局配置"],
        ["★bar.render('/root/eduhq/html/a.html')", "**render 不是 savefig**，产出 HTML"],
        ["WordCloud().add('', 数据, word_size_range=[20,100])", "词云"],
        ["Map().add('', 数据, 'china')", "中国地图（省份名要带「省/市」后缀才能匹配）"],
        ["⚠题目要「嵌入背景图」", "render 出的 HTML 需再插入背景样式，别忘了这一步"],
    ]},
    {"sec": "Python", "group": "sklearn 预测（2026 规程要求）", "cmds": [
        ["from sklearn.model_selection import train_test_split", "划分数据集"],
        ["X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)", "8:2 划分"],
        ["from sklearn.preprocessing import StandardScaler", "标准化（train 用 fit_transform，test 只 transform）"],
        ["from sklearn.ensemble import GradientBoostingRegressor", "回归模型"],
        ["model.fit(X_train, y_train)", "训练"],
        ["★from sklearn.metrics import r2_score", "**R² 决定系数，评分点**"],
        ["r2_score(y_test, y_pred)", "评估（越接近 1 越好）"],
    ]},

    # ---------------- Java ----------------
    {"sec": "Java", "group": "JDK 与编译运行", "cmds": [
        ["★java -version", "验证 JDK（本机 1.8.0_412）"],
        ["javac -version", "能打印说明装的是 JDK 不是 JRE"],
        ["★javac WordCount.java", "编译成 .class"],
        ["★java WordCount", "运行（**不要加 .class 后缀**）"],
        ["jar -cvf wc.jar *.class", "打成 jar"],
        ["hadoop jar wc.jar WordCount 输入 输出", "提交到集群跑"],
        ["⚠echo $JAVA_HOME", "必须指向 JDK 根目录，不是 bin；Hadoop 找不到它直接起不来"],
    ]},
    {"sec": "Java", "group": "语法速记（对比 Python）", "cmds": [
        ["int/long/double/boolean/String", "基本类型，变量必须先声明类型"],
        ["★s.equals(\"abc\")", "**字符串比较必须用 equals，== 比的是地址**（新手头号坑）"],
        ["s.length() / arr.length", "字符串长度有括号，数组长度没有"],
        ["for (int i = 0; i < n; i++)", "计数循环；for (String s : 列表) 增强 for"],
        ["StringBuilder sb = new StringBuilder()", "大量拼接字符串用它，别用 +"],
        ["public static void main(String[] args)", "固定入口签名"],
    ]},
    {"sec": "Java", "group": "Maven", "cmds": [
        ["mvn -v", "验证安装"],
        ["mvn clean package", "清 + 编 + 打包，产物在 target/"],
        ["mvn compile / mvn test", "只编译 / 跑测试"],
        ["pom.xml 的 <dependency>", "声明依赖：groupId + artifactId + version 坐标三要素"],
        ["⚠断网环境", "Maven 拉不到依赖，比赛环境一般备好本地仓库，别临时换版本"],
    ]},
    {"sec": "Java", "group": "MapReduce 骨架", "cmds": [
        ["class WcMapper extends Mapper<LongWritable, Text, Text, IntWritable>", "四个泛型 = 输入 K/V、输出 K/V"],
        ["context.write(new Text(word), new IntWritable(1))", "Map 端输出"],
        ["★protected void reduce(Text key, Iterable<IntWritable> values, Context ctx)", "同 key 的 value 全凑齐才调一次"],
        ["job.setJarByClass / setMapperClass / setReducerClass", "Driver 里配 Job"],
        ["job.setOutputKeyClass(Text.class); setOutputValueClass(IntWritable.class)", "设置输出类型"],
        ["FileInputFormat.addInputPath / FileOutputFormat.setOutputPath", "输入输出路径"],
        ["★job.waitForCompletion(true)", "提交并等待"],
        ["⚠输出目录必须不存在", "否则 Output directory already exists，跑之前先删"],
        ["⚠FileInputFormat 静默过滤 _/. 开头文件", "MR 输入别用这类文件名，否则数据凭空少一截"],
    ]},

    # ---------------- MySQL ----------------
    {"sec": "MySQL", "group": "连接与库表", "cmds": [
        ["★mysql -uroot -p", "登录（-p 后不要直接跟密码，回车后输入更安全）"],
        ["★USE education;", "**进库！建表前忘了 USE 就建到别的库里了**"],
        ["SHOW DATABASES; / SHOW TABLES;", "看库 / 看表"],
        ["★DESC 表名;", "看表结构"],
        ["CREATE DATABASE education DEFAULT CHARSET utf8mb4;", "建库（**中文必用 utf8mb4**）"],
        ["★CREATE TABLE t (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50) NOT NULL, age INT);", "建表模板"],
        ["DROP TABLE t; / DROP DATABASE db;", "删表 / 删库"],
        ["exit;", "退出（分号不能少）"],
    ]},
    {"sec": "MySQL", "group": "★增删改查 CRUD", "cmds": [
        ["★INSERT INTO t (name, age) VALUES ('张三', 18);", "插入"],
        ["★SELECT * FROM t WHERE age > 18;", "查询；SELECT 列1,列2 只取指定列"],
        ["★UPDATE t SET age = 20 WHERE id = 1;", "改；**不加 WHERE 会把整表都改了**"],
        ["★DELETE FROM t WHERE id = 1;", "删；**同样不能漏 WHERE**"],
        ["SELECT * FROM t LIMIT 10;", "限制条数；LIMIT 0,10 从第 0 条开始取 10 条"],
        ["SELECT * FROM t ORDER BY age DESC;", "排序（DESC 降序 / ASC 升序）"],
        ["★SELECT 省份, COUNT(*) FROM t GROUP BY 省份;", "分组统计"],
        ["⚠HAVING COUNT(*) > 10", "**分组后筛组用 HAVING，分组前筛行用 WHERE**"],
        ["SELECT * FROM a JOIN b ON a.id = b.id;", "连表；LEFT JOIN 保留左表全部"],
        ["LOAD DATA LOCAL INFILE '/root/a.csv' INTO TABLE t FIELDS TERMINATED BY ',';", "导入 CSV"],
    ]},
    {"sec": "MySQL", "group": "用户与权限（赛题常考）", "cmds": [
        ["★CREATE USER 'eduadmin'@'%' IDENTIFIED BY '******';", "建用户，@'%' = 允许任意主机连"],
        ["★GRANT ALL PRIVILEGES ON education.* TO 'eduadmin'@'%';", "授权"],
        ["★FLUSH PRIVILEGES;", "**不 FLUSH 权限不生效**，这是「授权了还是连不上」的头号原因"],
        ["ALTER USER 'root'@'localhost' IDENTIFIED BY '新密码';", "改密（5.7 写法）"],
        ["UPDATE mysql.user SET host='%' WHERE user='root';", "开 root 远程（改完同样要 FLUSH）"],
        ["SHOW GRANTS FOR 'eduadmin'@'%';", "查看已有权限"],
    ]},
    {"sec": "MySQL", "group": "备份与导入导出", "cmds": [
        ["mysqldump -uroot -p education > education.sql", "导出整个库"],
        ["mysql -uroot -p education < education.sql", "导入"],
        ["mysqldump -uroot -p education t1 t2 > part.sql", "只导出指定表"],
        ["SELECT ... INTO OUTFILE '/tmp/r.csv' FIELDS TERMINATED BY ',';", "导出 CSV"],
        ["⚠INTO OUTFILE 报权限错", "受 secure_file_priv 限制，换目录或改配置"],
    ]},

    # ---------------- 大数据 ----------------
    {"sec": "大数据", "group": "★HDFS 文件操作", "cmds": [
        ["★hdfs dfs -mkdir -p /behavior/origin_log", "级联建目录（-p 不能少）"],
        ["★hdfs dfs -put 本地文件 /目标路径", "上传；-f 覆盖已存在文件"],
        ["hdfs dfs -get /远程文件 本地路径", "下载"],
        ["★hdfs dfs -ls /  /  -ls -R /", "查看 / 递归查看"],
        ["★hdfs dfs -cat /路径/part-r-00000", "看结果文件内容"],
        ["hdfs dfs -rm -r /路径", "删除（-r 递归）"],
        ["hdfs dfs -du -h /", "看占用；hdfs dfs -count / 看文件数"],
        ["hdfs dfsadmin -report", "集群报告：容量、DataNode 存活"],
        ["⚠hdfs namenode -format", "**只在首次初始化执行一次**，重复格式化会丢全部数据"],
    ]},
    {"sec": "大数据", "group": "Hadoop 集群启停", "cmds": [
        ["★start-dfs.sh / stop-dfs.sh", "启停 HDFS"],
        ["★start-yarn.sh / stop-yarn.sh", "启停 YARN"],
        ["start-all.sh / stop-all.sh", "一键启停（不推荐，容易漏日志）"],
        ["mr-jobhistory-daemon.sh start historyserver", "起历史服务（看已完成任务）"],
        ["★jps", "验证四个进程都在"],
        ["http://主机:9870", "NameNode Web UI（看文件树）"],
        ["http://主机:8088", "YARN Web UI（看作业）"],
        ["http://主机:19888", "历史服务（看已完成作业）"],
        ["⚠root 运行 Hadoop 3.x", "必须在 hadoop-env.sh 显式写 6 个 *_USER=root"],
    ]},
    {"sec": "大数据", "group": "Hive", "cmds": [
        ["★hive -e \"SELECT 1;\"", "**最低限度可用性验证，装完必跑**"],
        ["hive", "进交互客户端；hive -f script.sql 执行脚本文件"],
        ["SHOW DATABASES; / USE db; / SHOW TABLES;", "库表查看"],
        ["★CREATE EXTERNAL TABLE t (id INT, name STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\\t' LOCATION '/path/';", "外部表模板（**外部表删表不删数据**）"],
        ["LOAD DATA INPATH '/hdfs/文件' INTO TABLE t;", "导入（INPATH 是 HDFS，加 LOCAL 是本地）"],
        ["LOAD DATA ... OVERWRITE INTO TABLE t;", "覆盖导入"],
        ["SELECT COUNT(*) FROM t;", "行数统计"],
        ["INSERT OVERWRITE LOCAL DIRECTORY '/root/result' ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' SELECT ...;", "导出结果到本地"],
        ["★DROP DATABASE db CASCADE;", "强制删库（有表时必须 CASCADE）"],
        ["schematool -dbType mysql -initSchema", "初始化元数据库（只做一次）"],
    ]},
    {"sec": "大数据", "group": "Kafka", "cmds": [
        ["★kafka-server-start.sh -daemon $KAFKA_HOME/config/server.properties", "启动（先起 ZooKeeper）"],
        ["★kafka-topics.sh --zookeeper localhost:2181 --list", "列 topic"],
        ["★kafka-topics.sh --zookeeper localhost:2181 --create --topic test --partitions 1 --replication-factor 1", "建 topic"],
        ["kafka-topics.sh --zookeeper localhost:2181 --describe --topic test", "详情（**Leader 不能是 -1**）"],
        ["★kafka-console-producer.sh --broker-list localhost:9092 --topic test", "生产消息（输入后 Ctrl+C）"],
        ["★kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning", "消费（**收到消息 = 链路打通**）"],
        ["kafka-topics.sh --zookeeper localhost:2181 --delete --topic test", "删 topic"],
        ["⚠Kafka 2.4.1 的 topics.sh 不支持 --bootstrap-server", "必须用 --zookeeper；用错只打印 usage 不报错"],
    ]},
    {"sec": "大数据", "group": "Spark", "cmds": [
        ["★spark-submit --class 主类 --master local[2] 包.jar 参数", "提交作业（本机 local 模式）"],
        ["run-example SparkPi 10", "跑内置样例"],
        ["spark-shell --master local[2]", "交互式 Scala"],
        ["pyspark", "Python 交互式"],
        ["★sc.textFile('/root/wc.txt').flatMap(_.split(\" \")).map((_,1)).reduceByKey(_+_).collect", "shell 里一行 wordcount"],
        ["spark-submit --master yarn --deploy-mode client ...", "YARN 模式提交"],
        ["http://主机:4040", "运行时 UI（作业结束就关了）"],
        ["http://主机:18080", "历史服务器"],
        ["⚠driver 堆下限 450MiB", "最小写 --driver-memory 512m"],
    ]},
    {"sec": "大数据", "group": "ZooKeeper / Flume / Sqoop", "cmds": [
        ["zkServer.sh start|status|stop", "启停 ZK；status 看 Mode"],
        ["zkCli.sh -server 主机:2181", "客户端；ls / 看节点，get 看值"],
        ["flume-ng version", "Flume 版本"],
        ["★flume-ng agent -n a1 -c conf -f /root/t.conf -Dflume.root.logger=INFO,console", "起 agent（-n 要和 conf 里 agent 名一致）"],
        ["sqoop version", "Sqoop 版本"],
        ["★sqoop list-databases --connect jdbc:mysql://master:3306/ --username root --password ******", "连通性验证"],
        ["★sqoop import --connect jdbc:mysql://master:3306/db --username root --password ****** --table t --target-dir /sqoop/t -m 1", "导入 HDFS（-m 1 单 map，小数据量用）"],
        ["sqoop export --connect ... --table t --export-dir /sqoop/t", "导出到数据库"],
        ["⚠缺 JDBC 驱动", "报 Could not load db driver class，把 mysql-connector 放进 $SQOOP_HOME/lib"],
    ]},
    {"sec": "大数据", "group": "HBase / Redis", "cmds": [
        ["start-hbase.sh / stop-hbase.sh", "启停 HBase（需先起 HDFS + ZK）"],
        ["hbase shell", "进 shell；echo \"status\\nexit\" | hbase shell 非交互"],
        ["★create 't1','cf'", "建表（**表名必须带引号**）"],
        ["put 't1','r1','cf:name','张三'", "写数据"],
        ["★scan 't1' / get 't1','r1'", "扫全表 / 取单行"],
        ["disable 't1' then drop 't1'", "**删表必须先 disable**"],
        ["http://主机:16010", "HMaster Web UI"],
        ["★redis-cli ping", "返回 **PONG**（Redis 的 hello world）"],
        ["redis-cli -a 口令 set k v / get k", "存取；keys * 看所有键；del k 删"],
        ["⚠设了 requirepass", "必须带 -a 口令，否则 NOAUTH"],
    ]},
    {"sec": "大数据", "group": "Docker 与本机运维", "cmds": [
        ["★bigdata-ctl status", "**一键看全部组件状态**（本机自制脚本）"],
        ["bigdata-ctl start all / stop all", "一键启停"],
        ["bigdata-ctl start hbase --kafka-off", "起 HBase 同时关 Kafka（4G 内存互斥）"],
        ["docker ps -a", "看容器；--format '{{.Names}}\\t{{.Status}}' 精简输出"],
        ["docker logs 容器名", "看日志；-f 实时"],
        ["docker compose up -d / down", "按 compose 启停"],
        ["docker images / docker rmi 镜像", "看镜像 / 删镜像"],
        ["⚠卡死的 pull", "pkill -x docker；**别用 pkill -f \"docker pull\"，会匹配自身 shell 自杀**"],
    ]},

    # ---------------- 赛场通用 ----------------
    {"sec": "赛场通用", "group": "★开考 10 分钟标准动作", "cmds": [
        ["1. free -h", "先看内存还剩多少，决定哪些组件能同时开"],
        ["2. jps", "看基础组件在不在"],
        ["3. ss -lntp", "确认端口没冲突"],
        ["4. 读题划重点", "圈出：输入输出路径、结果文件名、分隔符、字段顺序"],
        ["5. 建目录 mkdir -p", "按题目要求先把输出目录建好"],
        ["6. 边做边截图", "**每完成一个子任务立刻截图，别攒到最后**"],
    ]},
    {"sec": "赛场通用", "group": "★结果文件三查（交卷前必做）", "cmds": [
        ["查路径", "题目说 /root/eduhq/result/ 就别放 /tmp，路径错 = 0 分"],
        ["查文件名", "**文件名要带处理条数 N**（如 ads_province_1234.csv）"],
        ["查分隔符", "逗号还是 \\t，题目要求什么就用什么"],
        ["查编码", "中文用 utf-8 / utf8mb4，乱码就是白做"],
        ["查内容", "hdfs dfs -cat 或 cat 抽查前几行，确认字段顺序对"],
        ["查条数", "wc -l 确认行数与题目要求一致"],
    ]},
    {"sec": "赛场通用", "group": "⚠高频翻车点", "cmds": [
        ["mkdir 忘了 -p", "父目录不存在直接报错，级联建目录必须 -p"],
        ["输出目录已存在", "MR / Sqoop 都报 already exists，跑之前先删"],
        ["忘了 USE 库", "表建到别的库里，白干"],
        ["授权忘了 FLUSH", "FLUSH PRIVILEGES 不执行权限不生效"],
        ["改了 profile 没 source", "环境变量不生效，命令找不到"],
        ["中文乱码", "matplotlib 两行 rcParams / MySQL utf8mb4 / 文件 encoding"],
        ["Kafka topics.sh 参数用错", "2.4.1 必须用 --zookeeper，用错只打印 usage"],
        ["HBase 删表没先 disable", "直接 drop 会报错"],
        ["内存不够硬开组件", "Kafka 与 HBase 不可同时常驻，先 bigdata-ctl 看状态"],
        ["截图不带命令", "只截结果不截命令，证据不成立"],
    ]},
]
