# -*- coding: utf-8 -*-
"""组件「验证可用性」清单 —— 每个组件装完必须当场验证

赛项评分是按「结果」给分的：**验证过程的截图 = 得分证据**。
光把组件装上、服务起来了不算完，必须有一条能证明它真的能干活的证据链。

每个组件给出：验证命令 → 期望看到什么 → 截图截哪儿 → 失败时先查什么。
命令以 CentOS 7.9 + /opt/bigdata 布局为准（本机实际环境）。
"""

INTRO = {
    "why": "赛场评分看的是结果证据。组件装完不等于得分，只有「验证命令 + 期望输出」的截图才被认。",
    "rule": "**验证截图 = 得分证据**。一个组件至少留 2 张截图：① 服务活着（进程 / 端口 / 状态）　② 真能干活（跑一个小任务并看到正确结果）",
    "order": "按依赖顺序验证：JDK → SSH 免密 → Hadoop → ZooKeeper → MySQL → Hive → Kafka → Spark → Flink → HBase → Flume / Sqoop → Redis",
}

# 截图规范：学生最容易因为截图不合规被扣分
SHOT_RULES = [
    {"t": "命令和结果必须在同一张图里", "d": "只截结果不截命令，评委看不出你是怎么得到这个结果的 —— 整屏截，让人看清敲的是什么。"},
    {"t": "要能看出是「这台机器、这个目录」", "d": "终端提示符里有主机名和当前路径，别把窗口裁得只剩结果数字；必要时先 `hostname` 或 `pwd` 再执行。"},
    {"t": "结果要完整，不要只截一半", "d": "jps 截到只剩两个进程、hive 查询截不到返回值，都会被判证据不足。"},
    {"t": "一次成功就立刻截，别事后补", "d": "事后再跑一遍可能因为目录已存在而报错（`Output directory already exists`），反而变成反证。"},
    {"t": "失败也要截，并附排查过程", "d": "排查类题目里，「报错 + 定位 + 修复后成功」三张图的链条比一张成功图更有说服力。"},
    {"t": "按题目要求的路径和文件名存放", "d": "题目说放 `/root/eduhq/result/`，就别放 `/tmp`；截图命名也要按题目格式，乱放等于没交。"},
]

VERIFY = [
    {
        "id": "jdk", "name": "JDK（一切的前提）", "icon": "☕",
        "pre": "Hadoop / Hive / Spark / Flink / HBase 全是 Java 写的，JDK 没配好后面全废。",
        "steps": [
            {"cmd": "java -version", "expect": "输出 java version \"1.8.0_412\"（三行，含 OpenJDK Runtime）",
             "shot": "version 三行完整"},
            {"cmd": "echo $JAVA_HOME", "expect": "打印 JDK 根目录，如 /opt/bigdata/jdk1.8.0_412",
             "shot": "echo 输出"},
            {"cmd": "javac -version", "expect": "输出 javac 1.8.0_412 —— 说明装的是 JDK 不是 JRE",
             "shot": "javac 版本"},
        ],
        "pit": "JAVA_HOME 指向了 bin 目录或指向了 JRE；改完 /etc/profile 没 source 就不生效。",
    },
    {
        "id": "hadoop", "name": "Hadoop（HDFS + YARN）", "icon": "🐘",
        "pre": "先格式化 NameNode（只做一次！），再 start-dfs.sh / start-yarn.sh。",
        "steps": [
            {"cmd": "jps", "expect": "四个进程都在：NameNode、DataNode、ResourceManager、NodeManager",
             "shot": "jps 完整输出（缺一个都要回去查日志）"},
            {"cmd": "hdfs dfs -mkdir -p /test && hdfs dfs -ls /",
             "expect": "能列出 /test 目录，说明 HDFS 可写可读",
             "shot": "ls 结果里有 /test"},
            {"cmd": "echo 'hello hadoop hello hdfs' > /root/wc.txt\nhdfs dfs -put -f /root/wc.txt /test/\nhadoop jar $HADOOP_HOME/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.1.3.jar wordcount /test /out\nhdfs dfs -cat /out/part-r-00000",
             "expect": "输出 hello 2、hadoop 1、hdfs 1（顺序不定）",
             "shot": "**这条是 MR 真能跑的铁证**，cat 出来的词频结果必须截到"},
            {"cmd": "curl -s http://localhost:9870 | head -5",
             "expect": "返回 HTML，说明 NameNode Web UI 可用；浏览器打开可看文件树",
             "shot": "浏览器 9870 页面"},
        ],
        "pit": "以 root 运行必须在 hadoop-env.sh 显式写 6 个 *_USER=root；输出目录 /out 已存在会报 Output directory already exists，先 hdfs dfs -rm -r /out。",
    },
    {
        "id": "zk", "name": "ZooKeeper（Kafka / HBase 的依赖）", "icon": "🦁",
        "pre": "Kafka 与 HBase 都依赖 ZK，必须先起 ZK 再起它们。",
        "steps": [
            {"cmd": "zkServer.sh status", "expect": "Mode: standalone（单节点）或 leader/follower（集群）",
             "shot": "status 输出含 Mode"},
            {"cmd": "zkCli.sh -server localhost:2181 <<< 'ls /'",
             "expect": "返回 [zookeeper] 等节点列表，说明客户端连得上",
             "shot": "ls / 结果"},
            {"cmd": "echo stat | nc localhost 2181 | head -3",
             "expect": "返回 Zookeeper version 与客户端连接数（四字命令）",
             "shot": "stat 输出"},
        ],
        "pit": "AdminServer 默认 8081，与 MeTube 冲突，本机已改 8091；起不来先看 ss -lntp 有没有端口被占。",
    },
    {
        "id": "mysql", "name": "MySQL（Hive 元数据库）", "icon": "🗄️",
        "pre": "Hive 的元数据存在 MySQL，MySQL 起不来 Hive 一定起不来。",
        "steps": [
            {"cmd": "systemctl status mysqld", "expect": "active (running) 绿色字样",
             "shot": "status 输出"},
            {"cmd": "mysql -uroot -p -e \"SELECT VERSION();\"",
             "expect": "返回 5.7.xx 版本号",
             "shot": "版本号"},
            {"cmd": "mysql -uroot -p -e \"SHOW DATABASES;\"",
             "expect": "能看到 hive 库（Hive 初始化后才有）",
             "shot": "库列表里有 hive"},
            {"cmd": "mysql -uroot -p -e \"CREATE DATABASE IF NOT EXISTS vtest; USE vtest; CREATE TABLE t(id INT); INSERT INTO t VALUES(1); SELECT * FROM t; DROP DATABASE vtest;\"",
             "expect": "建库建表插入查询删除全通，最后 SELECT 返回 1",
             "shot": "**完整 CRUD 链路截图**，证明不只是能登录"},
        ],
        "pit": "MySQL 5.7 rpm 版 /etc/my.cnf 不含 !includedir /etc/my.cnf.d，需要手工追加否则 my.cnf.d 不生效；改 root 后记得 FLUSH PRIVILEGES。",
    },
    {
        "id": "hive", "name": "Hive（数据仓库）", "icon": "🐝",
        "pre": "先 schematool -dbType mysql -initSchema 初始化元数据，再启动 metastore / hiveserver2。",
        "steps": [
            {"cmd": "hive -e \"SELECT 1;\"", "expect": "返回 1（可能带一堆日志，最后一行是 1）",
             "shot": "**SELECT 1 返回 1 的截图，这是最低限度的可用性证据**"},
            {"cmd": "hive -e \"SHOW DATABASES;\"", "expect": "至少列出 default",
             "shot": "库列表"},
            {"cmd": "hive -e \"CREATE DATABASE IF NOT EXISTS vtest; USE vtest; CREATE TABLE IF NOT EXISTS t(id INT, name STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; INSERT INTO t VALUES(1,'zhangsan'); SELECT * FROM t; SELECT COUNT(*) FROM t;\"",
             "expect": "查到 1 条记录，COUNT 返回 1",
             "shot": "建表 + 插入 + 查询结果同框"},
            {"cmd": "hive -e \"DROP DATABASE vtest CASCADE;\"",
             "expect": "删除成功（清理现场，避免影响后续题目）",
             "shot": "可选"},
        ],
        "pit": "MySQL 没起 → Hive 报 Unable to instantiate SessionHiveMetaStoreClient；HDFS 没起 → 报找不到 /user/hive/warehouse。",
    },
    {
        "id": "kafka", "name": "Kafka（消息队列）", "icon": "📨",
        "pre": "必须先起 ZooKeeper，再起 Kafka。",
        "steps": [
            {"cmd": "kafka-topics.sh --zookeeper localhost:2181 --list",
             "expect": "能连通并返回 topic 列表（空列表也算成功）",
             "shot": "list 命令返回（不报错即可）"},
            {"cmd": "kafka-topics.sh --zookeeper localhost:2181 --create --topic vtest --partitions 1 --replication-factor 1\nkafka-topics.sh --zookeeper localhost:2181 --describe --topic vtest",
             "expect": "describe 返回 PartitionCount:1 ReplicationFactor:1，Leader 不为 -1",
             "shot": "**Leader 必须是非负整数**，为 -1 说明分区没选主"},
            {"cmd": "kafka-console-producer.sh --broker-list localhost:9092 --topic vtest\n# 输入 hello kafka 后 Ctrl+C 退出",
             "expect": "能进入输入状态不报错",
             "shot": "生产者输入画面"},
            {"cmd": "kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic vtest --from-beginning",
             "expect": "收到刚才发的 hello kafka",
             "shot": "**收到消息 = 生产消费链路打通的铁证**，必须截到消息内容"},
            {"cmd": "kafka-topics.sh --zookeeper localhost:2181 --delete --topic vtest",
             "expect": "删除成功（清理现场）",
             "shot": "可选"},
        ],
        "pit": "Kafka 2.4.1 的 kafka-topics.sh 不支持 --bootstrap-server，必须用 --zookeeper（用错只打印 usage 不报错，很容易误以为命令没写对）；server.properties 里 advertised.listeners 要写真实主机名。",
    },
    {
        "id": "spark", "name": "Spark（内存计算）", "icon": "⚡",
        "pre": "本机是 local 伪分布式，跑样例即可，不需要起集群。",
        "steps": [
            {"cmd": "spark-submit --version", "expect": "输出 version 3.1.1 与 Scala 版本",
             "shot": "版本信息"},
            {"cmd": "printf 'hello spark\\nhello hadoop\\nspark fast\\n' > /root/wc.txt\nspark-submit --master local[2] --class org.apache.spark.examples.JavaWordCount $SPARK_HOME/examples/jars/spark-examples_2.12-3.1.1.jar /root/wc.txt",
             "expect": "输出各单词计数：hello:2、spark:2、hadoop:1、fast:1",
             "shot": "**wordcount 结果截图 = Spark 可用的铁证**"},
            {"cmd": "run-example SparkPi 10 2>/dev/null | tail -3",
             "expect": "输出 Pi is roughly 3.14xxxx（每次略有不同）",
             "shot": "Pi 估算值"},
            {"cmd": "spark-shell --master local[2] <<< 'sc.parallelize(1 to 100).sum'",
             "expect": "返回 res0: Int = 5050",
             "shot": "可选：交互式验证"},
        ],
        "pit": "driver 堆下限 450MiB，最小要写 --driver-memory 512m；spark-examples 的 jar 名含 Scala 版本 2.12，用 tab 补全避免写错。",
    },
    {
        "id": "flink", "name": "Flink（流计算）", "icon": "🌊",
        "pre": "start-cluster.sh 起集群，Web UI 端口本机已改为 8083（避开 MeTube 的 8081）。",
        "steps": [
            {"cmd": "jps | grep -E 'StandaloneSessionClusterEntrypoint|TaskManagerRunner'",
             "expect": "两个进程都在",
             "shot": "jps 过滤结果"},
            {"cmd": "flink run $FLINK_HOME/examples/batch/WordCount.jar --input /root/wc.txt --output /root/flink_out",
             "expect": "Job has been submitted，完成后 cat /root/flink_out 能看到词频",
             "shot": "**提交成功 + 结果文件同框**"},
            {"cmd": "curl -s http://localhost:8083 | head -5",
             "expect": "返回 HTML，浏览器打开能看到 Task Slots 与已完成的作业",
             "shot": "浏览器 8083 页面"},
        ],
        "pit": "默认 8081 与 MeTube 冲突，必须先改 flink-conf.yaml 的 rest.port；Flink 集群约 1.8G 内存，4G 机器上别和 HBase 同时开。",
    },
    {
        "id": "hbase", "name": "HBase（列式数据库）", "icon": "🧱",
        "pre": "依赖 HDFS + ZooKeeper，两个都得起；start-hbase.sh 启动。",
        "steps": [
            {"cmd": "jps | grep -E 'HMaster|HRegionServer'", "expect": "两个进程都在",
             "shot": "jps 过滤结果"},
            {"cmd": "echo \"status\\nexit\" | hbase shell", "expect": "返回 1 active master, 0 backup masters, 1 servers",
             "shot": "status 输出"},
            {"cmd": "echo \"create 'vtest','cf'\\nput 'vtest','r1','cf:name','zhangsan'\\nscan 'vtest'\\ndisable 'vtest'\\ndrop 'vtest'\\nexit\" | hbase shell",
             "expect": "scan 返回 row1 的 name=zhangsan，最后 drop 成功",
             "shot": "**建表 → 写 → 读 → 删 全链路截图**"},
            {"cmd": "curl -s http://localhost:16010 | head -5",
             "expect": "返回 HTML，浏览器 16010 可看表列表",
             "shot": "浏览器 16010 页面"},
        ],
        "pit": "HBase 2.2.3 是 hadoop2 profile，必须加 hbase.unsafe.stream.capability.enforce=false + HBASE_CLASSPATH=$(hadoop classpath)；hbase shell 里表名必须带引号。",
    },
    {
        "id": "flume", "name": "Flume（日志采集）", "icon": "🚰",
        "pre": "写一个最小 conf：监听目录或端口 → sink 到 HDFS 或 logger。",
        "steps": [
            {"cmd": "flume-ng version", "expect": "输出 Flume 1.9.0 与 Source/Sink/Channel 版本",
             "shot": "版本信息"},
            {"cmd": "flume-ng agent -n a1 -c conf -f /root/test-flume.conf -Dflume.root.logger=INFO,console",
             "expect": "控制台出现 Sink 开始写文件、HDFS 上能查到落地的小文件",
             "shot": "**控制台日志 + hdfs dfs -ls 落地文件同框**"},
            {"cmd": "hdfs dfs -cat /flume/events/* 2>/dev/null | head -5",
             "expect": "能看到采集到的原始日志内容",
             "shot": "落地文件内容"},
        ],
        "pit": "sink 到 HDFS 时要先建好目标目录；agent 名称要和 conf 里 -n 后写的一致，不一致会报配置找不到。",
    },
    {
        "id": "sqoop", "name": "Sqoop（数据库 ↔ Hadoop）", "icon": "🔄",
        "pre": "需要 MySQL JDBC 驱动放进 $SQOOP_HOME/lib。",
        "steps": [
            {"cmd": "sqoop version", "expect": "输出 Sqoop 1.4.x",
             "shot": "版本信息"},
            {"cmd": "sqoop list-databases --connect jdbc:mysql://master:3306/ --username root --password ******",
             "expect": "返回 MySQL 里的库列表，含 education、hive",
             "shot": "**能连通 MySQL 并列出库 = Sqoop 配置正确**"},
            {"cmd": "sqoop import --connect jdbc:mysql://master:3306/education --username root --password ****** --table hotel_all --target-dir /sqoop/hotel_all -m 1",
             "expect": "Map 100% reduce 0%，完成后 hdfs dfs -ls /sqoop/hotel_all 有 part-m-00000",
             "shot": "导入完成 + HDFS 落地文件"},
        ],
        "pit": "缺 JDBC 驱动会报 Could not load db driver class；--target-dir 已存在会报错，先删。",
    },
    {
        "id": "redis", "name": "Redis（缓存）", "icon": "🔴",
        "pre": "最简单的一个，一条命令就能验完。",
        "steps": [
            {"cmd": "redis-cli ping", "expect": "**返回 PONG**（这就是用户点名要的那条）",
             "shot": "**PONG 截图**"},
            {"cmd": "redis-cli -a 口令 set vtest 'hello' && redis-cli -a 口令 get vtest",
             "expect": "先返回 OK，再返回 hello",
             "shot": "set / get 同框"},
            {"cmd": "redis-cli info server | head -5", "expect": "返回 redis_version:6.2.6 等",
             "shot": "版本信息"},
        ],
        "pit": "设了 requirepass 就必须带 -a 口令，否则 NOAUTH 报错；systemctl 里单元名是 redis 不是 redis-server。",
    },
    {
        "id": "python", "name": "Python 与数据分析库", "icon": "🐍",
        "pre": "模块二数据处理、模块三出图全靠它，必须先确认库都在。",
        "steps": [
            {"cmd": "python3 --version", "expect": "Python 3.7.9",
             "shot": "版本"},
            {"cmd": "python3 -c \"import pandas, numpy, matplotlib; print(pandas.__version__, numpy.__version__, matplotlib.__version__)\"",
             "expect": "打印三个版本号，不报 ImportError",
             "shot": "**三件套导入成功截图**"},
            {"cmd": "python3 -c \"import pyecharts; print(pyecharts.__version__)\"",
             "expect": "打印 pyecharts 版本（出交互图需要）",
             "shot": "pyecharts 版本"},
            {"cmd": "python3 -c \"import sklearn; print(sklearn.__version__)\"",
             "expect": "打印 sklearn 版本（2026 规程明确要求）",
             "shot": "sklearn 版本"},
        ],
        "pit": "CentOS 7 的 OpenSSL 锁 1.0.2k，必须降级 urllib3==1.26.20 + cryptography==41.0.7 + pyOpenSSL==24.0.0，否则 pip 装包一片红。",
    },
    {
        "id": "docker", "name": "Docker（可选环境）", "icon": "🐳",
        "pre": "部分辅助服务跑在容器里，Docker 挂了会影响配套工具。",
        "steps": [
            {"cmd": "docker version | head -6", "expect": "Client 与 Server 版本都出现（Server 报红说明守护进程没起）",
             "shot": "版本信息"},
            {"cmd": "docker run --rm hello-world",
             "expect": "输出 Hello from Docker!",
             "shot": "**跑通 hello-world = 镜像拉取与运行都正常**"},
            {"cmd": "docker ps --format '{{.Names}}\\t{{.Status}}'",
             "expect": "列出在跑的容器",
             "shot": "容器列表"},
        ],
        "pit": "Docker Hub DNS 被污染，必须配 registry-mirrors；data-root 已迁到 /data/docker 并加了 RequiresMountsFor=/data。",
    },
]
